name: Publish Docker image by tag
on:
  push:
    tags:
      - v*
jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # use tag for image_tag, example:'v1.2.3' -> '1.2.3'
      - name: Set image tag
        run: |
          IMAGE_TAG=${GITHUB_REF##*/v}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: GITHUB_RUNNER_VERSION=$(<github_runner-version)
          platforms: linux/arm/v7,linux/amd64
          push: true
          tags: ${{ github.repository_owner }}/github-actions-runner:latest,${{ github.repository_owner }}/github-actions-runner:$(echo ${IMAGE_TAG})
